---
application:
  name: "v"
  project: "corona"
  organization: "QoveryCommunity"
  storage:
  - name: "database.sqlite"
    size: "500"
    type: "hdd"
    mount_point: "D:\\Dev\\WEB_Ha-1\\database.sqlite"
routers:
- name: "main-v"
  routes:
  - application_name: "v"
    paths:
    - "/*"
